### ISSUE TITLE
侧边栏滑动bug

### ISSUE THREAD

**Issue by kx59717** [searchfe/lavas-template-vue-webshell#2]
在只有返回按钮的页面，此时从页面左侧也能滑入侧边栏，而且从左侧滑入侧边栏这个动作跟ios的左侧滑动返回冲突，建议只做滑动关闭侧边栏

**Comment by clark-t** [comment]
已修复
https://github.com/lavas-project/lavas-template-vue-appshell/commit/f73bc7cd9638b0e30db130d8c7c418e59d1b80e2

**Comment by kx59717** [comment]
现在在搜索页是无法滑动出现侧边栏了，但是出现一个新bug，滑动关闭侧边栏之后（注意是滑动关闭！）整个页面无法操作，看html结构侧边栏结构未删除opacity为0
