### ISSUE TITLE
init appshell 工程，npm run dev后出现下面的问题

### ISSUE THREAD

**Issue by lceric** [searchfe/lavas-template-vue-webshell#4]
运行npm run dev
![default](https://user-images.githubusercontent.com/25276032/31697450-2fc319da-b3ea-11e7-8480-fb1ffb67c5f7.png)
是vuetify包里面报的，不确定是否是vuetify自身的问题还是lavas的问题，请帮忙验证一下

**Comment by liuruoran88** [comment]
感谢您的提问，问题已解决，请参考：https://github.com/lavas-project/lavas/issues/15
