### ISSUE TITLE
拖拽view层会导致view层遮盖住底部导航

### ISSUE THREAD

**Issue by rurusgit** [searchfe/lavas-template-vue-webshell#5]
![_20171025104031](https://user-images.githubusercontent.com/24243075/31977931-93ca0f2e-b971-11e7-92a8-faa881b29ee9.jpg)

如上图，
尝试调整正了下木有搞定，
请教下该如何解决，多谢。

**Comment by PengXing** [comment]
拖拽是你自己写的？怎么写的呢？然后你尝试了哪些方法？我先参考一下

**Comment by rurusgit** [comment]
@PengXing 
这个是ios safari， 自带的弹性效果
我只是改变了“Lavas”的背景颜色，拖拽出弹性效果后，这个背景就会挡住底部导航

**Comment by PengXing** [comment]
设置 z-index 能解决问题吗？

**Comment by rurusgit** [comment]
其实是因为底部导航栏背景设置成了透明，所以拖到底部后，content部分的背景色就透过来了。我设置个背景色就好了，多谢。

**Comment by PengXing** [comment]
好的，那我把 issue 关了
