### ISSUE TITLE
`npm run dev`时生成的文件和`npm run build`不一样

### ISSUE THREAD

**Issue by NoraGithub** [searchfe/lavas-template-vue-webshell#8]
`npm run build`  的`index.html`有 引入`sw-register.js`

`npm run dev`访问localhost:8082 没有该文件，看控制台的application是没有service worker的。

令人疑惑。

**Comment by PengXing** [comment]
lavas 在开发模式下不会生成 service worker 相关的文件，因为会干扰调试，因此只有 build 之后才有 service worker
